### ISSUE TITLE
internationalization in linux

### ISSUE THREAD

**Issue by jason-braun-sociomantic-mouse** [mousemke/_val#10]
not sure if this is only linux, but umlauted letters do not come through correctly from the irc side of slack to the slack ui.

![screen shot 2015-01-12 at 13 14 50](https://cloud.githubusercontent.com/assets/4903570/5702661/0473069a-9a5d-11e4-9dd4-6b50451d84a3.png)

XChat 2.8.8, Ubuntu 12.4

**Comment by mousemke** [comment]
this was an encoding issue client side.  closing the issue
