### ISSUE TITLE
irc disabled

### ISSUE THREAD

**Issue by mousemke** [mousemke/_val#21]
we appear unable to support irc until this gets fixed

https://github.com/martynsmith/node-irc/issues/495

**Comment by trinitynet** [comment]
yeh, ive had this for a while IIRC just downgrade and its fixed

**Comment by trinitynet** [comment]
here: npm install irc@0.5.0

**Comment by mousemke** [comment]
@trinitynet you are totally my hero.  sucks to drop versions, but it also sucks to not support irc.  thanks!

**Comment by trinitynet** [comment]
no probs bro
